# Generated by Django 3.1.2 on 2020-11-12 09:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BicycleParking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
                ('number', models.IntegerField(default=0)),
                ('positionX', models.DecimalField(decimal_places=12, default=None, max_digits=40, null=True)),
                ('positionY', models.DecimalField(decimal_places=12, default=None, max_digits=40, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Estadia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placeUsed', models.IntegerField()),
                ('dateCreated', models.DateTimeField(default=django.utils.timezone.now)),
                ('userName', models.CharField(default=None, max_length=50)),
                ('isAnonymous', models.BooleanField(default=False)),
                ('isActive', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='MoveCamera',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placeNumber', models.IntegerField()),
                ('occupied', models.BooleanField(blank=True, default=False, null=True)),
                ('pathPhoto', models.CharField(max_length=200)),
                ('createDate', models.CharField(default=None, max_length=200)),
                ('registered', models.BooleanField(blank=True, default=False, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userName', models.CharField(max_length=200)),
                ('photoPath', models.CharField(max_length=200)),
                ('place', models.IntegerField(default=None)),
            ],
        ),
        migrations.CreateModel(
            name='Segment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('segmentType', models.CharField(default=None, max_length=8)),
                ('photoPath', models.CharField(max_length=200)),
                ('datetime', models.DateTimeField(default=django.utils.timezone.now)),
                ('estadia', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='parkings.estadia')),
            ],
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placeNumber', models.IntegerField()),
                ('occupied', models.BooleanField(blank=True, default=False, null=True)),
                ('bicycleParking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parkings.bicycleparking')),
            ],
        ),
        migrations.CreateModel(
            name='PendingStay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userName', models.CharField(default=None, max_length=50)),
                ('isAuthorize', models.BooleanField(blank=True, default=None, null=True)),
                ('dateCreated', models.DateTimeField(default=django.utils.timezone.now)),
                ('stay', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parkings.estadia')),
            ],
        ),
        migrations.CreateModel(
            name='NotificationEgress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userName', models.CharField(max_length=200)),
                ('photoPath', models.CharField(max_length=200)),
                ('place', models.IntegerField(default=None)),
                ('isOk', models.BooleanField(blank=True, default=True, null=True)),
                ('isSuspected', models.BooleanField(blank=True, default=False, null=True)),
                ('dateCreated', models.DateTimeField(default=django.utils.timezone.now)),
                ('estadia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parkings.estadia')),
            ],
        ),
        migrations.AddField(
            model_name='estadia',
            name='place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parkings.place'),
        ),
        migrations.CreateModel(
            name='BikeOwner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bicyclePhoto', models.CharField(max_length=200)),
                ('profilePhoto', models.CharField(max_length=200)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
