# Generated by Django 3.1.1 on 2020-11-13 17:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parkings', '0002_auto_20201112_2011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estadia',
            name='place',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='parkings.place'),
        ),
    ]
