# Generated by Django 3.1.2 on 2020-11-13 19:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parkings', '0002_auto_20201112_2011'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notificationegress',
            old_name='isOk',
            new_name='isActive',
        ),
        migrations.AlterField(
            model_name='estadia',
            name='place',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='parkings.place'),
        ),
        migrations.AlterField(
            model_name='notificationegress',
            name='isSuspected',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
    ]
