# Generated by Django 3.1.1 on 2020-11-14 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parkings', '0003_auto_20201113_1734'),
        ('parkings', '0003_auto_20201113_1946'),
    ]

    operations = [
    ]
