# Generated by Django 3.1.1 on 2020-11-15 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parkings', '0004_merge_20201114_1836'),
        ('parkings', '0004_merge_20201114_1830'),
    ]

    operations = [
    ]
