# Generated by Django 3.1.2 on 2020-11-18 22:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parkings', '0005_merge_20201115_1241'),
    ]

    operations = [
        migrations.RenameField(
            model_name='segment',
            old_name='datetime',
            new_name='dateCreated',
        ),
    ]
