# Generated by Django 3.1.2 on 2020-11-24 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkings', '0006_auto_20201118_2235'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendingstay',
            name='isActive',
            field=models.BooleanField(default=True),
        ),
    ]
