# Generated by Django 3.1.2 on 2020-11-25 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkings', '0007_pendingstay_isactive'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendingstay',
            name='notifyToUser',
            field=models.BooleanField(default=False),
        ),
    ]
