# Generated by Django 3.1.2 on 2020-11-29 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parkings', '0008_pendingstay_notifytouser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification',
        ),
        migrations.RemoveField(
            model_name='notificationegress',
            name='photoPath',
        ),
        migrations.RemoveField(
            model_name='notificationegress',
            name='place',
        ),
    ]
