# Generated by Django 3.1.2 on 2020-10-16 22:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parkings', '0009_bicycleparking'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userName', models.CharField(max_length=200)),
                ('photoPath', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placeNumber', models.IntegerField()),
                ('occupied', models.BooleanField(blank=True, default=False, null=True)),
                ('bicycleParking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parkings.bicycleparking')),
            ],
        ),
    ]
