# Generated by Django 3.1.2 on 2020-11-30 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkings', '0010_configuration'),
    ]

    operations = [
        migrations.RenameField(
            model_name='configuration',
            old_name='secondsPending',
            new_name='configurationValue',
        ),
        migrations.AddField(
            model_name='configuration',
            name='configurationName',
            field=models.CharField(default=None, max_length=200),
        ),
    ]
