# Generated by Django 3.1.2 on 2020-10-16 22:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parkings', '0011_estadia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estadia',
            name='arrival',
        ),
        migrations.AddField(
            model_name='segment',
            name='estadia',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='parkings.estadia'),
        ),
    ]
