# Generated by Django 3.1.2 on 2020-10-17 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkings', '0012_auto_20201016_2247'),
    ]

    operations = [
        migrations.CreateModel(
            name='MoveCamera',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placeNumber', models.IntegerField()),
                ('occupied', models.BooleanField(blank=True, default=False, null=True)),
                ('pathPhoto', models.CharField(max_length=200)),
                ('hourGenerated', models.CharField(max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='Configuration',
        ),
        migrations.DeleteModel(
            name='Parkings',
        ),
    ]
