# Generated by Django 3.1.2 on 2020-11-30 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkings', '0012_auto_20201130_0922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuration',
            name='configurationName',
            field=models.CharField(default='config', max_length=200, null=True),
        ),
    ]
