# Generated by Django 3.1.2 on 2020-10-18 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkings', '0013_auto_20201017_0050'),
    ]

    operations = [
        migrations.AddField(
            model_name='segment',
            name='typeSegment',
            field=models.CharField(default=None, max_length=8),
        ),
    ]
