# Generated by Django 3.1.2 on 2020-12-08 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkings', '0014_auto_20201208_2012'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationegress',
            name='photoInBase64',
            field=models.TextField(default=''),
        ),
    ]
