# Generated by Django 3.1.2 on 2020-10-18 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkings', '0014_segment_typesegment'),
    ]

    operations = [
        migrations.AddField(
            model_name='movecamera',
            name='registered',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
