# Generated by Django 3.1.2 on 2020-10-18 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkings', '0015_movecamera_registered'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estadia',
            name='placeUsed',
            field=models.IntegerField(),
        ),
    ]
