# Generated by Django 3.1.2 on 2020-12-09 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parkings', '0016_auto_20201209_1349'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='estadia',
            unique_together=set(),
        ),
    ]
