# Generated by Django 3.1.2 on 2020-10-18 23:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('parkings', '0016_auto_20201018_2100'),
    ]

    operations = [
        migrations.AddField(
            model_name='estadia',
            name='dateCreated',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
