# Generated by Django 3.1.1 on 2020-10-19 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkings', '0017_estadia_datecreated'),
    ]

    operations = [
        migrations.AddField(
            model_name='bicycleparking',
            name='number',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='estadia',
            name='userEmail',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
