# Generated by Django 3.1.1 on 2020-10-25 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkings', '0018_auto_20201019_1648'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movecamera',
            name='hourGenerated',
        ),
        migrations.AddField(
            model_name='movecamera',
            name='createDate',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AddField(
            model_name='notification',
            name='place',
            field=models.IntegerField(default=None),
        ),
    ]
