# Generated by Django 3.1.2 on 2020-10-25 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkings', '0018_auto_20201019_1648'),
    ]

    operations = [
        migrations.AddField(
            model_name='bicycleparking',
            name='positionX',
            field=models.DecimalField(decimal_places=20, default=None, max_digits=40),
        ),
        migrations.AddField(
            model_name='bicycleparking',
            name='positionY',
            field=models.DecimalField(decimal_places=20, default=None, max_digits=40),
        ),
    ]
