# Generated by Django 3.1.2 on 2020-10-25 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkings', '0019_auto_20201025_2156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bicycleparking',
            name='positionX',
            field=models.DecimalField(decimal_places=12, default=None, max_digits=40),
        ),
        migrations.AlterField(
            model_name='bicycleparking',
            name='positionY',
            field=models.DecimalField(decimal_places=12, default=None, max_digits=40),
        ),
    ]
